name: UIKit
description: Bindings for UIApplication
language: objc
output: generated/generated_bindings.dart
exclude-all-by-default: true
objc-interfaces:
  include:
    - 'UIApplication'
headers:
  entry-points:
    - '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/iOSSupport/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h'
preamble: |
  // ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field, return_of_invalid_type, void_checks, annotate_overrides, no_leading_underscores_for_local_identifiers, library_private_types_in_public_api
